spring:
  rabbitmq:
    host: rabbit.tacocloud.com
    port: 5673
    username: tacoweb
    password: l3tm31n
    template:
      exchange: tacocloud.order
      routing-key: kitchens.central
  data:
    rest:
      base-path: /data-api
  security:
    user:
      name: buzz
      password: infinity
  datasource:
    generate-unique-name: false
    name: tacocloud

taco:
  orders:
    pageSize: 10


  discount:
    codes:
      abcdef: 10

